name:                ShellCheck
version:             0.11.0
github:              "koalaman/shellcheck"
license:             GPL-3
author:              "Vidar Holen"
maintainer:          "vidar@vidarholen.net"
# copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md
#- documentation
- shellcheck.1.md
#- A script to build the man page using pandoc
- manpage
#- convenience script for stripping tests
- striptests
#- tests
- test/shellcheck.hs

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description: |
  The goals of ShellCheck are:
  .
  * To point out and clarify typical beginner's syntax issues,
    that causes a shell to give cryptic error messages.
  .
  * To point out and clarify typical intermediate level semantic problems,
    that causes a shell to behave strangely and counter-intuitively.
  .
  * To point out subtle caveats, corner cases and pitfalls, that may cause an
    advanced user's otherwise working script to fail under future circumstances.

dependencies:
- aeson
- array
- base
- bytestring
- containers
- deepseq
- directory
- Diff
- fgl
- filepath
- mtl
- parsec
- QuickCheck
- regex-tdfa
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  shellcheck:
    main:                shellcheck.hs
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - ShellCheck

tests:
  test-shellcheck:
    main:                test/shellcheck.hs
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - ShellCheck
